model:
  name: "UNet"
  in_channels: 3
  out_channels: 1

training:
  resume_training: False
  resume_model_path: "../saved_models/train_20260202-141458/best_model.pth"  # Chemin du modèle à reprendre
  n_epochs: 3
  learning_rate: 0.0001
  batch_size: 8
  patience: 5
  epsilon: 0.5

data:
  train_img_path: "../data/train/original/"
  train_label_path: "../data/train/ground_truth/"
  test_img_path: "../data/test/original/"
  test_label_path: "../data/test/ground_truth/"
  image_size: 128
  train_split: 0.8

paths:
  save_dir: "../saved_models/"